<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\NET\Sesion10\PruebasUnitariasSolucion\PruebasLibrary\bin\Debug\PruebasLibrary.dll" total="1" errors="0" failures="1" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2015-06-07" time="10:57:04">
  <environment nunit-version="2.6.4.14350" clr-version="2.0.50727.5485" os-version="Microsoft Windows NT 6.1.7601 Service Pack 1" platform="Win32NT" cwd="C:\Program Files (x86)\NUnit 2.6.4\bin" machine-name="CINST-102SO" user="Profesor" user-domain="CINST-102SO" />
  <culture-info current-culture="es-ES" current-uiculture="es-ES" />
  <test-suite type="Assembly" name="C:\NET\Sesion10\PruebasUnitariasSolucion\PruebasLibrary\bin\Debug\PruebasLibrary.dll" executed="True" result="Failure" success="False" time="0.106" asserts="0">
    <results>
      <test-suite type="Namespace" name="PruebasLibrary" executed="True" result="Failure" success="False" time="0.082" asserts="0">
        <results>
          <test-suite type="TestFixture" name="TestClass2" executed="True" result="Failure" success="False" time="0.079" asserts="0">
            <results>
              <test-case name="PruebasLibrary.TestClass2.WithdrawTest" executed="True" result="Failure" success="False" time="0.063" asserts="1">
                <failure>
                  <message><![CDATA[PruebasLibrary.ExceededException was expected]]></message>
                  <stack-trace />
                </failure>
              </test-case>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>